name: Build RootHide DEB

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract project
        run: |
          unzip InputBridge-RootHide.zip

      - name: Install RootHide Theos
        run: |
          echo "THEOS=$HOME/theos" >> "$GITHUB_ENV"
          export THEOS="$HOME/theos"
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/roothide/theos/master/bin/install-theos)"

      - name: Build
        run: |
          cd InputBridge-RootHide
          make clean
          make package THEOS_PACKAGE_SCHEME=roothide

      - name: Upload DEB
        uses: actions/upload-artifact@v4
        with:
          name: InputBridge-RootHide
          path: InputBridge-RootHide/packages/*.deb
